import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const engines=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const root=fileURLToPath(new URL('../',import.meta.url));await mkdir(path.join(root,'test-results'),{recursive:true});
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://test').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await engines[process.env.BROWSER_ENGINE||'chromium'].launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const b=(p,name)=>p.getByRole('button',{name,exact:true});
const wait=async(fn,label)=>{for(let i=0;i<240;i++){if(await fn())return;await new Promise(r=>setTimeout(r,30));}throw Error('Timeout '+label);};
const settle=async p=>{await wait(()=>p.evaluate(async()=>!(await import('/modules/sync-events.js')).phoneSyncStatus(window).busy),'sync finished');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));};

try{for(const tt of [false,true]){
 const context=await browser.newContext({viewport:{width:393,height:740}}),p=await context.newPage(),errors=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.addInitScript({content:await readFile(path.join(root,'tests/profile-mock.js'),'utf8')});if(tt)await p.addInitScript({content:await readFile(path.join(root,'tests/tt-mock.js'),'utf8')});else await p.route('**/api/users/me',r=>r.fulfill({json:{handle:'test-user'}}));await p.addInitScript({content:await readFile(path.join(root,'tests/sync-mock.js'),'utf8')});
 await p.goto(base+'/preview.html');await b(p,'打开消息').click();await b(p,'我').click();await b(p,'我的名片').click();await p.getByLabel('微信号（剧情）',{exact:true}).fill('my_story_123');await b(p,'保存我的名片').click();await wait(async()=>(await p.locator('.profile-status').textContent()).includes('已保存到当前存档'),'self saved');await b(p,'取消').click();await b(p,'联系人').click();await b(p,'登记人物').click();await b(p,'手动创建人物').click();await p.getByLabel('人物名字',{exact:true}).fill('朋友甲');await p.getByLabel('微信号（剧情）',{exact:true}).fill('friend_story_123');await p.getByLabel('开局关系',{exact:true}).selectOption('known');await p.getByLabel('剧情加好友联动',{exact:true}).check();await b(p,'保存人物').click();await wait(async()=>(await p.locator('.profile-status').textContent()).includes('已保存到当前存档'),'person saved');await b(p,'取消').click();await b(p,'返回').click();await b(p,'新的朋友').click();
 const getBook=()=>p.evaluate(async()=>{const {createProfileHost}=await import('/modules/host.js');const h=createProfileHost(window);try{return (await h.load(new AbortController().signal)).book;}finally{h.dispose();}});
 let book=await getBook();assert.equal(book.self.account,'my_story_123');assert.equal(book.people[0].account,'friend_story_123');assert(!book.people[0].relation.friend);
 await p.evaluate(()=>profileMock.emit('GENERATION_AFTER_COMMANDS','normal'));const prompt=await p.evaluate(()=>Object.values(profileMock.friendPrompts)[0]?.value);assert(prompt.includes('my_story_123'));assert(prompt.includes('friend_story_123'));
 const emitEvent=async(type,id)=>p.evaluate(async({type,id})=>{const {createProfileHost}=await import('/modules/host.js');const h=createProfileHost(window),s=await h.load(new AbortController().signal);h.dispose();const person=s.book.people[0],event={id,archiveId:s.book.id,personId:person.id,type,account:type==='share_self'||type==='request_incoming'?s.book.self.account:person.account,note:'<img onerror=alert(1)> 验证'};profileMock.story.push({is_user:false,mes:'<content>角色给出账号，或按情节处理申请。</content>\n<!-- yui-friend '+JSON.stringify(event)+' -->'});profileMock.saveBody();},{type,id});
 await emitEvent('share_character','share_event_01');await b(p,'刷新事件与申请').click();await wait(()=>b(p,'确认此事件').count(),'event');assert.equal(await p.locator('.friend-card img').count(),0);await b(p,'确认此事件').click();await wait(async()=>(await getBook()).people[0].relation.accountKnown,'account known');book=await getBook();assert(!book.people[0].relation.friend);
 await p.getByLabel('搜索微信号',{exact:true}).fill('friend_story_123');await b(p,'搜索').click();await p.getByLabel('好友验证消息',{exact:true}).fill('我是刚才一起打游戏的');await b(p,'发送好友申请').click();await wait(()=>b(p,'取消申请').count(),'request');book=await getBook();assert(!book.people[0].relation.friend);assert.equal(book.people[0].friendRequest.note,'我是刚才一起打游戏的');
 await p.evaluate(()=>profileMock.emit('GENERATION_AFTER_COMMANDS','normal'));assert((await p.evaluate(()=>Object.values(profileMock.friendPrompts)[0].value)).includes('我是刚才一起打游戏的'));
 await emitEvent('accepted','accept_event_01');await b(p,'刷新事件与申请').click();await wait(()=>b(p,'确认此事件').count(),'accept event');await b(p,'确认此事件').click();await wait(async()=>(await getBook()).people[0].relation.friend,'accepted');await b(p,'返回').click();await b(p,'查看联系人：朋友甲').click();await b(p,'发消息').click();assert(await p.getByLabel('消息输入框',{exact:true}).isVisible());
 await p.reload();await b(p,'打开消息').click();await b(p,'新的朋友').click();await b(p,'刷新事件与申请').click();await p.waitForTimeout(150);assert.equal(await b(p,'确认此事件').count(),0);assert((await getBook()).people[0].relation.friend);
 // A second stranger demonstrates incoming proposals and rejection without befriending.
 await b(p,'管理剧情人物').click();await b(p,'登记人物').click();await b(p,'手动创建人物').click();await p.getByLabel('人物名字',{exact:true}).fill('朋友乙');await p.getByLabel('微信号（剧情）',{exact:true}).fill('second_123');await p.getByLabel('剧情加好友联动',{exact:true}).check();await b(p,'保存人物').click();await wait(async()=>(await p.locator('.profile-status').textContent()).includes('已保存到当前存档'),'second saved');await b(p,'取消').click();await b(p,'返回').click();await b(p,'新的朋友').click();
 await p.evaluate(async()=>{const {createProfileHost}=await import('/modules/host.js');const h=createProfileHost(window),s=await h.load(new AbortController().signal);h.dispose();const e={id:'incoming_event_02',archiveId:s.book.id,personId:s.book.people[1].id,type:'request_incoming',account:s.book.self.account,note:'你好，我是朋友乙'};profileMock.story.push({is_user:false,mes:'<content>他发来了好友申请。</content>\n<!-- yui-friend '+JSON.stringify(e)+' -->'});profileMock.saveBody();});await b(p,'刷新事件与申请').click();await wait(()=>b(p,'确认此事件').count(),'incoming event');await b(p,'确认此事件').click();await wait(()=>b(p,'通过申请').count(),'inbound saved');assert(!(await getBook()).people[1].relation.friend);
 await p.setViewportSize({width:320,height:540});if(tt)await p.evaluate(()=>ttMock.emitLayout({version:1,safeFrame:{left:0,top:24,width:320,height:516},ime:{keyboardOffset:0}}));assert(await p.locator('.friend-page').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:path.join(root,'test-results/friends-'+(tt?'tt':'st')+'-'+(process.env.BROWSER_ENGINE||'chromium')+'.png')});
 await b(p,'拒绝申请').click();await wait(async()=>!(await getBook()).people[1].friendRequest,'rejected');assert(!(await getBook()).people[1].relation.friend);assert.deepEqual(errors,[]);console.log('PASS '+(tt?'TT':'ST')+' editable accounts, opt-in prompt, source confirmation, outgoing/incoming requests, acceptance/rejection, reload and 320px');await context.close();
}}finally{await browser.close();server.close();}
