import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const engines=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const root=fileURLToPath(new URL('../',import.meta.url));await mkdir(path.join(root,'test-results'),{recursive:true});
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://test').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await engines[process.env.BROWSER_ENGINE||'chromium'].launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const b=(p,name)=>p.getByRole('button',{name,exact:true});
const wait=async(fn,label)=>{for(let i=0;i<240;i++){if(await fn())return;await new Promise(r=>setTimeout(r,30));}throw Error('Timeout '+label);};
const settle=async p=>{await wait(()=>p.evaluate(async()=>!(await import('/modules/sync-events.js')).phoneSyncStatus(window).busy),'sync finished');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));};

try{for(const tt of [false,true]){
 const context=await browser.newContext({viewport:{width:393,height:740}}),p=await context.newPage(),errors=[],requests=[];p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript({content:await readFile(path.join(root,'tests/profile-mock.js'),'utf8')});if(tt)await p.addInitScript({content:await readFile(path.join(root,'tests/tt-mock.js'),'utf8')});else await p.route('**/api/users/me',r=>r.fulfill({json:{handle:'test-user'}}));await p.addInitScript({content:await readFile(path.join(root,'tests/sync-mock.js'),'utf8')});
 await p.route('https://ai.fixture.test/**',async r=>{if(r.request().method()==='OPTIONS'){await r.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'}});return;}requests.push(r.request().postDataJSON());await r.fulfill({json:{choices:[{message:{content:'这局一起走下路。'},finish_reason:'stop'}]}});});
 await p.goto(base+'/preview.html');await p.evaluate(async()=>{
  const {createProfileHost}=await import('/modules/host.js'),{newPerson,defaultStoryPolicy}=await import('/modules/contacts.js'),{saveConfig,defaultConfig}=await import('/modules/ai.js');
  saveConfig(window,{...defaultConfig(),baseUrl:'https://ai.fixture.test/v1',model:'fixture',historyCount:1});
  const host=createProfileHost(window),signal=new AbortController().signal,session=await host.load(signal),person=newPerson(undefined,'测试好友');person.relation={known:true,accountKnown:true,friend:true};person.storyContext={...defaultStoryPolicy(),sharePhone:true,phoneCount:200};const book=structuredClone(session.book);book.people.push(person);book.storySync={enabled:true,excludedIds:[]};await host.save(session,book,signal);host.dispose();
 });
 const open=async()=>{await b(p,'打开消息').click();await b(p,'打开聊天：测试好友').click();};
 await p.reload();await open();await p.getByLabel('消息输入框',{exact:true}).fill('保留聊天草稿');await b(p,'添加附件').click();assert.equal(await p.locator('.attachment-tool').count(),3);await b(p,'旁白').click();await p.getByLabel('旁白内容',{exact:true}).fill('此时是王者内部私聊');await p.getByLabel('持续作为当前场景',{exact:true}).check();
 await p.setViewportSize({width:320,height:540});if(tt)await p.evaluate(()=>ttMock.emitLayout({version:1,safeFrame:{left:0,top:24,width:320,height:516},ime:{keyboardOffset:0}}));
 assert(await p.locator('.attachment-panel').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:path.join(root,'test-results/narration-panel-'+(tt?'tt':'st')+'-'+(process.env.BROWSER_ENGINE||'chromium')+'.png')});
 await b(p,'关闭附件面板').click();await b(p,'添加附件').click();await b(p,'旁白').click();assert.equal(await p.getByLabel('旁白内容',{exact:true}).inputValue(),'此时是王者内部私聊');await b(p,'添加旁白').click();await wait(()=>p.locator('.phone-narration:not(.pending-message)').count(),'saved narration');await settle(p);assert.equal(requests.length,0);assert.equal(await p.getByLabel('消息输入框',{exact:true}).inputValue(),'保留聊天草稿');assert.equal(await p.locator('.phone-narration img').count(),0);assert.equal(await p.locator('.narration-tag').textContent(),'当前场景');
 await p.getByLabel('消息输入框',{exact:true}).fill('来开一局');await b(p,'发送').click();await wait(()=>p.locator('.real-messages').getByText('来开一局',{exact:true}).count(),'chat saved');await settle(p);await p.waitForTimeout(850);await b(p,'让对方回复').click();await wait(()=>requests.length===1,'AI request');assert(JSON.stringify(requests[0].messages).includes('currentPhoneScene'));assert(JSON.stringify(requests[0].messages).includes('此时是王者内部私聊'));await wait(()=>p.locator('.real-messages').getByText('这局一起走下路。',{exact:true}).count(),'reply saved');await settle(p);
 await b(p,'添加附件').click();await b(p,'旁白').click();assert.equal(await p.getByLabel('旁白内容',{exact:true}).inputValue(),'');await p.getByLabel('旁白内容',{exact:true}).fill('现在已经切回微信');await p.getByLabel('持续作为当前场景',{exact:true}).check();await b(p,'添加旁白').click();await wait(async()=>await p.locator('.phone-narration:not(.pending-message)').count()===2,'second scene');await settle(p);
 const last=p.locator('.phone-narration .narration-text').last();await last.scrollIntoViewIfNeeded();await settle(p);await last.dispatchEvent('contextmenu');await b(p,'编辑').click();await p.getByLabel('编辑消息内容',{exact:true}).fill('现在切回QQ');assert(await p.getByLabel('持续作为当前场景',{exact:true}).isChecked());await b(p,'保存消息修改').click();await wait(()=>p.locator('.phone-narration').getByText('现在切回QQ',{exact:true}).count(),'edit');await settle(p);
 await p.evaluate(()=>profileMock.emit('GENERATION_AFTER_COMMANDS','normal'));assert((await p.evaluate(()=>profileMock.story[0].mes)).includes('旁白（持续场景'));assert((await p.evaluate(()=>profileMock.story[0].mes)).includes('现在切回QQ'));
 await p.evaluate(async()=>{const m=profileMock.story[0];m.mes=m.mes.replace('现在切回QQ','回到微信了');await profileMock.emit('MESSAGE_UPDATED',0);});await wait(()=>p.locator('.phone-narration').getByText('回到微信了',{exact:true}).count(),'pencil edit');await settle(p);
 await p.reload();await open();assert.equal(await p.locator('.phone-narration').count(),2);await p.locator('.chat-history-info summary').click();assert((await p.locator('.current-scene-reference').textContent()).includes('回到微信了'));
 const target=p.locator('.phone-narration .narration-text').last();await target.scrollIntoViewIfNeeded();await settle(p);await target.dispatchEvent('contextmenu');await b(p,'删除').click();await b(p,'确认删除消息').click();await wait(async()=>await p.locator('.phone-narration').count()===1,'delete');await settle(p);assert(!(await p.evaluate(()=>profileMock.story[0].mes)).includes('回到微信了'));assert.equal(await p.locator('.narration-tag').textContent(),'当前场景');
 await p.screenshot({path:path.join(root,'test-results/narration-chat-'+(tt?'tt':'st')+'-'+(process.env.BROWSER_ENGINE||'chromium')+'.png')});assert.deepEqual(errors,[]);console.log('PASS '+(tt?'TT':'ST')+' narration UI, draft, no automatic reply, actual scene prompt, edit/delete, story sync and reload');await context.close();
}}finally{await browser.close();server.close();}
