import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const engines=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const root=fileURLToPath(new URL('../',import.meta.url));await mkdir(path.join(root,'test-results'),{recursive:true});
const server=createServer(async(req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://test').pathname);if(!file.startsWith(root)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await engines[process.env.BROWSER_ENGINE||'chromium'].launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const b=(p,name)=>p.getByRole('button',{name,exact:true});
const wait=async(fn,label)=>{for(let i=0;i<240;i++){if(await fn())return;await new Promise(r=>setTimeout(r,30));}throw Error('Timeout '+label);};
const key='yui-glass-phone.presets.v1';
async function home(p){await b(p,'返回手机桌面').click();}
async function more(p){const menu=p.getByRole('button',{name:'预设操作',exact:true});if(await menu.getAttribute('aria-expanded')!=='true')await menu.click();}
async function names(p){await more(p);const d=p.locator('.preset-manage');if(await d.getAttribute('open')===null)await d.locator('summary').click();}
async function choose(p,id){if(await b(p,'返回预设列表').count())await b(p,'返回预设列表').click();await p.locator('.preset-card[data-preset-id="'+id+'"]').locator('.preset-card-main').click();}
async function settings(p){await home(p);await b(p,'打开设置').click();await b(p,'聊天预设').click();}
try{for(const tt of [false,true]){
 const context=await browser.newContext({viewport:{width:393,height:740},acceptDownloads:true}),p=await context.newPage();p.setDefaultTimeout(8000);const errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.addInitScript({content:await readFile(path.join(root,'tests/profile-mock.js'),'utf8')});if(tt)await p.addInitScript({content:await readFile(path.join(root,'tests/tt-mock.js'),'utf8')});else await p.route('**/api/users/me',r=>r.fulfill({json:{handle:'test-user'}}));
 let delay=false,release;await p.route('https://preset.fixture/**',async r=>{if(r.request().method()==='OPTIONS'){await r.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'}});return;}requests.push(r.request().postDataJSON());if(delay)await new Promise(resolve=>release=resolve);await r.fulfill({json:{choices:[{message:{content:'正常回复'},finish_reason:'stop'}]}}).catch(()=>{});});
 await p.goto(base+'/preview.html');await p.evaluate(()=>localStorage.setItem('yui-glass-phone.ai.v1',JSON.stringify({version:1,baseUrl:'https://preset.fixture/v1',apiKey:'fixture-secret',model:'fixture',prompt:'旧风格保留',frontPrompt:'旧前置保留'})));
 await settings(p);assert((await p.locator('.preset-card.is-active').getAttribute('data-preset-id'))!=='builtin');assert.equal(await p.evaluate(k=>localStorage.getItem(k),key),null);await b(p,'保存预设设置').click();let stored=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(stored.presets.length,2);assert.equal(stored.presets[1].blocks[0].content,'旧前置保留');
 await choose(p,'builtin');assert(await b(p,'添加条目').isDisabled());assert.equal(await b(p,'删除此预设').count(),0);await more(p);await b(p,'复制预设').click();await names(p);await p.getByLabel('预设名称',{exact:true}).fill('我的预设');await b(p,'预设操作').click();await p.locator('.preset-block summary').click();await p.getByLabel('条目内容',{exact:true}).fill('发送给角色的风格 <img onerror=alert(1)>');await p.screenshot({path:path.join(root,`test-results/presets-edit-${tt?'tt':'st'}.png`)});
 await b(p,'添加条目').click();await p.getByLabel('条目名称',{exact:true}).last().fill('前置要求');await p.getByLabel('条目内容',{exact:true}).last().fill('{{user}}和{{char}}排在前面');await p.locator('.preset-block').last().getByRole('button',{name:'上移',exact:true}).click();assert((await p.locator('.preset-block summary').first().textContent()).includes('前置要求'));
 // Disable a populated entry, and remove another entry before persisting.
 await b(p,'添加条目').click();await p.getByLabel('条目名称',{exact:true}).last().fill('关闭条目');await p.getByLabel('条目内容',{exact:true}).last().fill('不应该发送的内容');await p.locator('.preset-block').last().getByRole('checkbox').uncheck();
 await b(p,'添加条目').click();await p.getByLabel('条目内容',{exact:true}).last().fill('删除条目内容');await p.locator('.preset-block').last().getByRole('button',{name:'删除条目',exact:true}).click();assert.equal(await p.locator('.preset-block').count(),3);
 await b(p,'使用此预设').click();await b(p,'保存预设设置').click();const activeId=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).activeId,key);assert.equal(await p.locator('.preset-content img').count(),0);assert((await p.locator('.preset-block[open]').count())<=1);
 await more(p);const download=p.waitForEvent('download');await b(p,'导出预设').click();const file=await download,exported=JSON.parse(await readFile(await file.path(),'utf8'));assert.equal(exported.yuiPhonePreset,1);assert(!JSON.stringify(exported).includes('fixture-secret'));
 // Cancel draft and failed save preserve the previous saved library.
 const original=await p.evaluate(k=>localStorage.getItem(k),key);await names(p);await p.getByLabel('预设名称',{exact:true}).fill('未保存名字');await more(p);await b(p,'取消未保存修改').click();assert.equal(await p.getByLabel('预设名称',{exact:true}).inputValue(),'我的预设');
 await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('yui-glass-phone.presets'))throw Error('quota');return window.originalSet.call(this,k,v);};});await names(p);await p.getByLabel('预设名称',{exact:true}).fill('保存失败草稿');await b(p,'保存预设设置').click();assert((await p.locator('.profile-status').textContent()).includes('草稿保留'));assert.equal(await p.getByLabel('预设名称',{exact:true}).inputValue(),'保存失败草稿');assert.equal(await p.evaluate(k=>localStorage.getItem(k),key),original);await p.evaluate(()=>Storage.prototype.setItem=window.originalSet);await more(p);await b(p,'取消未保存修改').click();
 // Foreign markers cannot silently become working features; duplicate IDs are reported.
 const external={__nuojijiChatPreset:true,name:'外部预设',mode:'online',blocks:[{id:'dup',key:'soul',type:'marker'},{id:'dup',key:'context',type:'marker'},{id:'f',key:'format',type:'marker'},{id:'t',type:'custom',name:'外部文字',content:'保持简洁',enabled:true}]};
 await p.getByLabel('导入聊天预设文件').setInputFiles({name:'fixture.nuopreset.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(external))});await b(p,'确认导入为新预设').waitFor();assert((await p.locator('.preset-import').textContent()).includes('重复'));assert((await p.locator('.preset-import').textContent()).includes('未映射'));await b(p,'确认导入为新预设').click();assert.equal(await p.getByLabel('预设名称',{exact:true}).inputValue(),'外部预设');await b(p,'保存预设设置').click();
 // Deleting the active preset requires a chosen replacement. Cancel and switch back.
 await choose(p,activeId);await names(p);await b(p,'删除此预设').click();assert((await p.locator('.profile-status').textContent()).includes('替代'));assert.equal(await p.locator('.preset-manager .toolbar h1').textContent(),'我的预设');
 await b(p,'返回预设列表').click();await p.screenshot({path:path.join(root,`test-results/presets-list-${tt?'tt':'st'}.png`)});await choose(p,activeId);
 assert.equal(await p.locator('.preset-block[open]').count(),0);await p.getByLabel('搜索条目名称或内容').fill('关闭条目');assert.equal(await p.locator('.preset-block:visible').count(),1);await p.locator('.preset-block:visible input[type=checkbox]').check();assert.equal(await p.locator('.preset-block[open]').count(),0);await p.locator('.preset-block:visible input[type=checkbox]').uncheck();await p.getByLabel('搜索条目名称或内容').fill('');await b(p,'保存预设设置').click();
 await p.setViewportSize({width:320,height:540});assert(await b(p,'保存预设设置').isVisible());const overflow=await p.locator('.preset-manager .directory-scroll').evaluate(e=>e.scrollWidth-e.clientWidth);assert(overflow<=1);await p.setViewportSize({width:393,height:740});
 const density=await p.locator('.preset-row-head').first().evaluate(el=>({height:el.getBoundingClientRect().height,font:getComputedStyle(el.querySelector('strong')).fontSize}));assert(density.height<60);assert.equal(density.font,'11px');await p.screenshot({path:path.join(root,`test-results/presets-${tt?'tt':'st'}.png`)});
 await home(p);await b(p,'打开消息').click();await b(p,'联系人').click();await b(p,'登记人物').click();await b(p,'手动创建人物').click();await p.getByLabel('人物名字',{exact:true}).fill('朋友');await p.getByLabel('开局关系',{exact:true}).selectOption('friend');await b(p,'保存人物').click();await wait(async()=> (await p.locator('.profile-status').textContent()).includes('已保存'),'person');await b(p,'取消').click();
 await settings(p);await choose(p,activeId);await more(p);await b(p,'预览发送内容').click();await b(p,'读取当前存档好友').click();await wait(async()=> (await p.getByLabel('预览好友').locator('option').count())===2,'friends');const friendId=await p.getByLabel('预览好友').locator('option').last().getAttribute('value');await p.getByLabel('预览好友').selectOption(friendId);await b(p,'预览发送内容').click();await wait(async()=> (await p.locator('.profile-status').textContent()).includes('没有发送给 AI'),'preview');const preview=await p.locator('.preset-preview .profile-material').allTextContents();assert.equal(preview[0],'测试用户人设和朋友排在前面');assert(!preview.join('').includes('不应该发送的内容'));assert(!preview.join('').includes('删除条目内容'));assert.equal(requests.length,0);assert.equal(await p.locator('.preset-preview img').count(),0);
 await home(p);await b(p,'打开消息').click();await b(p,'打开聊天：朋友').click();await b(p,'让对方回复').click();await wait(()=>requests.length===1,'request');assert.deepEqual(requests[0].messages.map(m=>m.content),preview);await wait(()=>p.getByText('正常回复',{exact:true}).count(),'saved');
 // New preset settings during request discard the stale response without creating a second bubble.
 delay=true;await b(p,'让对方回复').click();await wait(()=>!!release,'delay');await p.evaluate(k=>{const v=JSON.parse(localStorage.getItem(k));v.activeId='builtin';v.revision++;localStorage.setItem(k,JSON.stringify(v));},key);delay=false;release();await wait(()=>b(p,'灵动岛：查看回复提示').count(),'stale');assert.equal(await p.getByText('正常回复',{exact:true}).count(),1);
 await settings(p);await choose(p,activeId);await names(p);await b(p,'使用此预设').click();await b(p,'保存预设设置').click();await names(p);await p.getByLabel('删除后的替代预设').selectOption('builtin');await b(p,'删除此预设').click();await b(p,'保存预设设置').click();assert.equal(await p.locator('.preset-card.is-active').getAttribute('data-preset-id'),'builtin');await p.reload();await b(p,'打开设置').click();await b(p,'聊天预设').click();assert.equal(await p.locator('.preset-card.is-active').getAttribute('data-preset-id'),'builtin');
 // Optional local-only real file regression. Never commits its content or sends it to AI.
 if(process.env.USER_PRESET_FILE){
  const source=JSON.parse(await readFile(process.env.USER_PRESET_FILE,'utf8')),blocks=source.blocks.filter(b=>b.type==='custom');const requestsBefore=requests.length;
  await p.getByLabel('导入聊天预设文件').setInputFiles(process.env.USER_PRESET_FILE);await b(p,'确认导入为新预设').waitFor();assert((await p.locator('.preset-import').textContent()).includes('可编辑文字 '+blocks.length+' 条'));await b(p,'确认导入为新预设').click();await b(p,'保存预设设置').click();assert((await p.locator('.profile-status').textContent()).includes('已保存在本机'));
  const values=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).presets.at(-1).blocks,key),fields=b=>({name:b.name,content:b.content,role:b.role,enabled:b.enabled});assert.deepEqual(values.map(fields),blocks.map(fields));await p.locator('.preset-manager .directory-scroll').evaluate(e=>e.scrollTop=0);await p.screenshot({path:path.join(root,`test-results/presets-large-${tt?'tt':'st'}.png`)});await p.reload();await b(p,'打开设置').click();await b(p,'聊天预设').click();assert.equal(await b(p,'编辑预设：'+source.name).count(),1);assert.equal(requests.length,requestsBefore);console.log('PASS local supplied preset: '+blocks.length+' text blocks preserved and reloaded; no AI request');
 }
 assert.deepEqual(errors,[]);console.log(`PASS ${tt?'TT':'ST'} presets: migration, lock, edit/order, import report, export, cancel/failure, deletion, exact request preview, stale reply and refresh`);await context.close();
}}finally{await browser.close();server.close();}
