import {newBook,newPerson,defaultStoryPolicy,clone} from '../modules/contacts.js';
import {createMessageStore} from '../modules/message-host.js';
export function supplementFixture(tt=false){
 const book=newBook(),person=newPerson(undefined,'朋友');person.relation={known:true,accountKnown:true,friend:true};person.storyContext={...defaultStoryPolicy(),sharePhone:true};book.people.push(person);book.storySync={enabled:true,excludedIds:[]};
 const session={book,account:tt?'tt-native':'u',snapshot:{chatId:'A',source:{avatarFile:'a.png'},group:false}},data=new Map(),listeners=new Map();let active=true,pause;
 const state={writes:0,failWrite:false,failAfterWrite:false,pauseWrite:null,disk:[],stop:0};
 const ai={name:'朋友',is_user:false,is_system:false,mes:'<content>酒吧门口</content>\n<!-- QQJ-end | date=2026-10-05 | time=21:30 | weekday=周一 -->',extra:{keep:1},swipe_id:0};ai.swipes=[ai.mes,'另一个回复'];ai.swipe_info=[{extra:{keep:1}},{extra:{other:1}}];
 const ctx={chat:[ai],characters:[{avatar:'a.png',name:'朋友'}],characterId:0,chatMetadata:{integrity:'archive-A'},getRequestHeaders:()=>({}),stopGeneration(){state.stop++;},extensionPrompts:{other:{value:'keep'}},eventTypes:Object.fromEntries(['MESSAGE_UPDATED','MESSAGE_SENT','GENERATION_AFTER_COMMANDS','GENERATION_STARTED','GENERATION_ENDED','GENERATION_STOPPED','CHAT_CHANGED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_DELETED'].map(n=>[n,n])),eventSource:{on(e,fn){if(!listeners.has(e))listeners.set(e,new Set());listeners.get(e).add(fn);},removeListener(e,fn){listeners.get(e)?.delete(fn);}}};state.disk=clone(ctx.chat);
 async function save(chat){state.writes++;if(state.pauseWrite)await state.pauseWrite;if(state.failWrite)throw Error('磁盘写入失败');state.disk=clone(chat);if(state.failAfterWrite){state.failAfterWrite=false;state.failRead=true;}}
 async function read(){if(state.failRead){state.failRead=false;throw Error('读回中断');}return clone(state.disk);}
 const win={crypto,SillyTavern:{getContext:()=>ctx},navigator:{locks:{request:async(k,o,fn)=>fn()}},localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},async fetch(url,options){if(url==='/api/chats/get')return {ok:true,json:async()=>[{chat_metadata:{integrity:'archive-A'}},...await read()]};if(url==='/api/chats/save'){const payload=JSON.parse(options.body);await save(payload.chat.slice(1));return {ok:true};}throw Error('Unexpected fetch '+url);}};
 if(tt){win.__TAURITAVERN__={api:{chat:{open:()=>({history:{tail:async({limit})=>{const messages=await read();return {startIndex:Math.max(0,messages.length-limit),messages:messages.slice(-limit)};}},store:{listKeys:async()=>[...data.keys()],getJson:async({key})=>clone(data.get(key)),setJson:async({key,value})=>data.set(key,clone(value)),renameKey(){}}})}}};ctx.saveChat=async()=>save(ctx.chat);}
 ctx.saveChat=async()=>save(ctx.chat);
 const profiles={assertSession(s,signal){if(!active||signal.aborted)throw Error('切档');},async load(signal){if(pause)await pause;this.assertSession(session,signal);return clone(session);}},signal=new AbortController().signal,store=createMessageStore(win,profiles,session,signal);
 return {win,profiles,ctx,person,book,store,session,listeners,state,async emit(e,...args){for(const fn of [...(listeners.get(e)||[])])await fn(...args);},setActive:v=>active=v,setPause:v=>pause=v};
}
